repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.12
    hooks:
      # Run import sorting
      - id: ruff
        name: ruff import sort
        args: 
          - "--select I" 
          - "--fix"
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
